version: "3.7"
services:
  duckhunt:
    build: .
    ports:
      - 8086:80
      - 2345:2345
    privileged: true
    env_file:
    - ./env/credentials.env
    entrypoint: ["dlv", "debug", "/go/src/duckhunt", "--headless", "--listen=:2345", "--log", "--api-version=2"]
    # command: ["go", "run", "github.com/basraven/duckhunt"]
    volumes:
      - ../:/go/src/duckhunt
    links:
      - db
  db:
    logging:
        driver: none
    environment:
    - POSTGRES_PASSWORD=duckhunt
    - POSTGRES_USER=duckhunt
    - POSTGRES_DB=duckhunt
    image: postgres