# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: duckhunt-env
#   namespace: duckhunt
# data:
#   credentials.env: |-
#     TELEGRAM_API_KEY=
#     CHAT_ID=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: duckhunt
  namespace: duckhunt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: duckhunt
        k8s-app: duckhunt
    spec:
      containers:
      - name: duckhunt
        ports:
        - containerPort: 80
        env:
        - name: TELEGRAM_API_KEY
          value: ""
        image: golang:alpine
        command: [ "/bin/sh" ]
        args: ["-c", "apk add git && go get -u github.com/basraven/duckhunt && go build github.com/basraven/duckhunt && duckhunt"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: duckhunt
    kubernetes.io/name: duckhunt
  name: duckhunt
  namespace: duckhunt
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: duckhunt
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: duckhunt
  namespace: duckhunt
spec:
  rules:
  - host: duckhunt.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: duckhunt
          servicePort: 80